apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: ecommerce
  labels:
    app: frontend
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
        - name: frontend
          image: sachinn9700/ecommerce-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

              